# -*- coding: utf-8 -*-
"""trabalho pbe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tzFUZWb9BeML7EcpaTTCCg2Jcr8a6Z_8
"""

#1
nome = "joão"

print(nome)

#2
a = 5
b = 10

soma = a + b
sub = a - b
mult = a * b
div = a / b

print(soma, sub, mult, div)

#3
preco = 50
desconto = 10

print(f" O desconto é de {preco-desconto}")

#4
resultado = 10+5*2

print(resultado)

#5

valor = "150"
int_valor = int(valor)

print(int_valor/2)

#7

a = int(input("Digite um valor: "))
b = int(input("Digite um valor: "))

print(f"A soma dos valores {a} + {b} é {a+b}")

#8

x = int(input("Digite um valor: "))
y = int(input("Digite um valor: "))

print(f"A divisão inteira de {x} por {y} é {x//y}")

#9

num1 = int(input("Digite um valor: "))
num2 = int(input("Digite um valor: "))

print(f"O valor {num1} é maior que {num2}? {num1>num2}")

#10

idade = int(input("Digite sua idade"))

print(f" Você viveu {idade*365}")

#11

base = int(input("Digite a base: "))
expoente = int(input("Digite o expoente: "))

print(f"O valor {base} elevado a {expoente} é {base**expoente}")

#12

preco = int(input("Digite o valor: "))

str_preco = str(preco)

print(f"O preço é R${str_preco}")

#13

raio = int(input("Digite o valor do raio: "))

print(f"A área do circulo é {3.14*(raio*raio)}")

#14

a = int(input("Digite um valor: "))
b = int(input("Digite um valor: "))

a = a+b
b = a-b
a = a-b

print(a,b)

#15

nota1 = int(input("Digite nota 1: "))
nota2 = int(input("Digite nota 2: "))
nota3 = int(input("Digite nota 3: "))

media = (nota1*2 + nota2*3 + nota3*5)/2+3+5

print(f"Média ponderada é {media}")

#16

x1 = int(input("Digite o valor valor 1 do ponto a: "))
x2 = int(input("Digite o valor valor 2 do ponto a: "))
y1 = int(input("Digite o valor valor 1 do ponto b: "))
y2 = int(input("Digite o valor valor 2 do ponto b: "))

distancia = ((x2 - x1) ** 2 + (y2 - y1) ** 2)**(1/2)


print(f"A distancia entre a e b é: {distancia}")