# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18GJaJdkw2K2XKc7vyjvHXaPGf9c53WR6
"""

#1 par ou impar

num = int(input("Digite um número: "))

if num%2==0:
  print("O número é par!")

else:
  print("O número é ímpar")

#2 se é maior que 10

num = int(input("Digite um número: "))

if num>10:
  print("O núemro é maior que 10")

elif num==10:
  print("O número é o 10")

else:
  print("O número é menor que 10")

#3 menor maior de idade

idade = int(input("Digite sua idade: "))

if idade >=18:
  print("Você é maior de idade")

else:
  print("Você é menor de idade")

#4 voto obrigatório opcional ou não tem voto

idade = int(input("Digite sua idade: "))

if idade >=16 and idade <18 or idade>=70:
  print("Seu voto é facultativo")

elif idade >=18 and idade <70:
  print("Seu voto é obrigatório")

else:
   print("Você não pode votar")

#5 positivo negativo

num = int(input("Digite um número: "))

if num >=0:
  print("O número é positivo")

else:
  print("O número é negativo")

#6 notas

nota = int(input("Digite sua nota: "))


if nota <3:
  print("Sua nota é E")

elif nota <5:
  print("Sua nota é D")

elif nota <7:
  print("Sua nota é C")

elif nota <9:
  print("Sua nota é B")

elif nota == 9 or nota==10:
  print("Sua nota é A")

#7

idade = int(input("Digite sua idade: "))

if idade<=12 or idade>=60:
  print("Tem diteito a desconto!")

else:
  print("Não tem direito  desconto")

#8

c1 = int(input("Digite o 1° comprimento: "))
c2 = int(input("Digite o 2° comprimento: "))
c3 = int(input("Digite o 3° comprimento: "))


if (c1+c2 >c3) and (c2+c3 >c1) and (c1+c3 >c2):

   if (c1 == c2) and (c1 == c3) and (c2 == c3):
       print("O triângulo é equilátero")

   elif (c1 != c2) and (c1 != c3) and (c2 != c3):
       print("O triângulo é escaleno")

   elif (c1 == c2) or (c2 == c3) or (c1==c3):
       print("O triângulo é isósceles")
else:
   print("Os comprimentos não podem formar um triângulo")

#9 desconto

valor = float(input("Digite o valor total da compra: R$"))

if valor<100:
  print(f"o desconto é de %5, o valor ficará: R${valor-(valor*(5/100))}")

elif valor>=100 or valor<=500:
  print(f"O desconto é de 10%, o valor ficará: R${valor-(valor*(10/100))}")

elif valor>500:
  print(f"O desconto é de 15%, o valor ficará: R${valor-(valor*(15/100))}")

#10 ano bissexto

ano = int(input("Digite um ano: "))
if ano%4 == 0 and ano%100 != 0 or ano % 400 == 0:
  print("O ano é bissexto")
else:
  print("Não é bissexto")

#11 imc

peso = float(input("Digite seu peso: "))
altura = float(input("Digite sua altura: "))
imc = peso/(altura*altura)
print(f"Seu imc é {imc}")
if imc <= 18.5:
  print("Você está abaixo do peso")
elif imc <= 24.9:
  print("Você está com imc normal")
elif imc <= 29.9:
  print("Você está com sobrepeso")
elif imc>30:
  print("Você está com obesidade")

#12 crescente decrescente

num1 = int(input("Digite um número em ordem crescente ou descrescente: "))
num2 = int(input("Digite um número: "))
num3 = int(input("Digite um número: "))

if num1>num2>num3:
  print("Decrescente")

elif num1<num2<num3:
  print("Crescente")

elif num1==num2==num3:
  print("Os números são iguais")

else:
  ("Ordem inválida")

#13 temperatura

temp = int(input("Digite a temperatura em celcius: "))

if temp<10:
  print("Frio")

elif temp>=10 or temp<25:
  print("Acochengante")

elif temp>25 or temp<40:
  print("Quente")

elif temp>40:
  print("Muito quenteeeeee")

  r"^

#14 data inverter

dia = int(input("Digite o dia: "))
mes = int(input("Digite o mês: "))
ano = int(input("Digite o ano: "))

print(f"A data é {ano}/{mes}/{dia}")

#15 senha
import re

print("▶ Sua senha deve conter: \n → Pelo menos 8 caracteres \n → Pelo menos uma letra maiúscula \n → Pelo menos uma letra minúscula \n → Pelo menos um número \n → Pelo menos um caractere especial (@,#,$,%,&)")
senha = input("▶ Digite sua senha: ")

if len(senha)<8:
  print("A senha não tem o mínimo de caracteres!")

elif not re.search("[A-Z]", senha):
  print("Falta pelo menos uma letra maiúscula!")

elif not re.search("[a-z]", senha):
  print("Falta pelo menos uma letra minúscula!")

elif not re.search("[0-9]",senha):
  print("Falta pelo menos um número!")

elif not re.search("[@#$%&]", senha):
  print("Falta pelo menos um caractere especial!")

else:
  print("Senha válida!")

#16 raiz

raiz = int(input("Digite um número para calcular raiz a quadrada: "))
raizquadrada = raiz ** 0.5

if raiz > 100:
  print("Número muito grande, reduza para um valor abaixo de 100")

elif raiz < 0:
  print("Não é possível calcular a raiz quadrada de um número negativo")

else:
  print(f"A raiz quadrada de {raiz} é {raizquadrada:.2f}")

#17 data

data = input("Digite a data (dd/mm/aaaa): ")
partes = data.split("/")
dia = int(partes[0])
mes = int(partes[1])
ano = int(partes[2])


if 1 <= mes <= 12:
    if mes in [1, 3, 5, 7, 8, 10, 12]:
        if 1 <= dia <= 31:
            data_formatada = f"{ano}/{mes:02d}/{dia:02d}"
            print("Data no formato aaaa/mm/dd:", data_formatada)
        else:
            print("Data inválida! Esse mês tem apenas 31 dias.")

    elif mes in [4, 6, 9, 11]:
        if 1 <= dia <= 30:
            data_formatada = f"{ano}/{mes:02d}/{dia:02d}"
            print("Data no formato aaaa/mm/dd:", data_formatada)
        else:
            print("Data inválida! Esse mês tem apenas 30 dias.")

    elif mes == 2:
        if (ano % 4 == 0 and ano % 100 != 0) or (ano % 400 == 0):
            if 1 <= dia <= 29:
                data_formatada = f"{ano}/{mes:02d}/{dia:02d}"
                print("Data no formato aaaa/mm/dd:", data_formatada)
            else:
                print("Data inválida! Esse mês tem apenas 29 dias.")
        else:
            if 1 <= dia <= 28:
                data_formatada = f"{ano}/{mes:02d}/{dia:02d}"
                print("Data no formato aaaa/mm/dd:", data_formatada)
            else:
                print("Data inválida! Esse mês tem apenas 28 dias.")
else:
    print("Mês inválido! Digite um mês de 1 a 12.")

#18 expresão matemática

expre = input("Digite uma expressão matemática: ")

print(f"O resultado da expressão é {eval(expre)}")

#19 cpf

import re

def validar_cpf(cpf: str) -> bool:
    if not re.match(r'^\d{3}\.\d{3}\.\d{3}-\d{2}$', cpf):
        return False

    cpf = ''.join([c for c in cpf if c.isdigit()])

    if len(cpf) != 11:
        return False

    if cpf == cpf[0] * 11:
        return False

    soma_1 = sum(int(cpf[i]) * (10 - i) for i in range(9))
    digito_1 = (soma_1 * 10 % 11) % 10

    soma_2 = sum(int(cpf[i]) * (11 - i) for i in range(10))
    digito_2 = (soma_2 * 10 % 11) % 10


    return cpf[-2:] == f"{digito_1}{digito_2}"

cpf = input("Digite seu CPF: ")
if validar_cpf(cpf):
    print("CPF válido!")
else:
    print("CPF inválido!")